### ISSUE TITLE
同一时间内备份的问题

### ISSUE THREAD

**Issue by CoffeeChou** [ovirt-china/vm-backup-scheduler#6]
## 描述
* 当虚拟机的备份策略设置在同一时间，或时间比较接近时，会导致备份失败。即不进行备份。

### 运行中的虚拟机
1. 选择一台运行中的虚拟机。
1. 设置两个备份策略，其中一个为【增量备份】，另一个为【完全备份】。
1. 设置备份时间相同，即同时进行备份。

* 结果

  到了备份时间，进行完全备份，而没有进行增量备份，即没有创建备份快照，只创建了完全备份中所使用的temp快照，完全备份结束后，没有进行增量备份。

### 两台虚拟机备份时间接近
1. 设置第一台虚拟机的备份策略为【完全备份】。
1. 设置第二台虚拟机的备份策略为【完全备份】或增量备份，备份时间比第一台虚拟机稍微晚一些。

* 结果

  到了备份时间，第一台虚拟机进行完全备份，而到了第二台虚拟机进行备份的时间，由于第一台虚拟机的备份还未完成，影响了第二台虚拟机的备份，第二台虚拟机没有进行备份（即使第一台虚拟机备份结束，第二台虚拟机仍然没有进行备份）。

**Comment by walteryang47** [comment]
fixed in above commit
